package com.entitys;
// Generated 30-oct-2016 12:42:32 by Hibernate Tools 4.3.1



/**
 * Telefonos generated by hbm2java
 */
public class Telefonos  implements java.io.Serializable {


     private String telefonoArea;
     private String telefono;
     private String password;
     private String codigoArea;
     private String codigoConfirm;
     private String status;
     private String idUsuario;

    public Telefonos() {
    }

	
    public Telefonos(String telefonoArea, String telefono, String password, String codigoArea, String idUsuario) {
        this.telefonoArea = telefonoArea;
        this.telefono = telefono;
        this.password = password;
        this.codigoArea = codigoArea;
        this.idUsuario = idUsuario;
    }
    public Telefonos(String telefonoArea, String telefono, String password, String codigoArea, String codigoConfirm, String status, String idUsuario) {
       this.telefonoArea = telefonoArea;
       this.telefono = telefono;
       this.password = password;
       this.codigoArea = codigoArea;
       this.codigoConfirm = codigoConfirm;
       this.status = status;
       this.idUsuario = idUsuario;
    }
   
    public String getTelefonoArea() {
        return this.telefonoArea;
    }
    
    public void setTelefonoArea(String telefonoArea) {
        this.telefonoArea = telefonoArea;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getCodigoArea() {
        return this.codigoArea;
    }
    
    public void setCodigoArea(String codigoArea) {
        this.codigoArea = codigoArea;
    }
    public String getCodigoConfirm() {
        return this.codigoConfirm;
    }
    
    public void setCodigoConfirm(String codigoConfirm) {
        this.codigoConfirm = codigoConfirm;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }




}


