package com.entitys;
// Generated 30-oct-2016 12:42:32 by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private String idUsuario;
     private String nombres;
     private String apellidos;
     private String pais;
     private String email;
     private String status;

    public Usuarios() {
    }

	
    public Usuarios(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Usuarios(String idUsuario, String nombres, String apellidos, String pais, String email, String status) {
       this.idUsuario = idUsuario;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.pais = pais;
       this.email = email;
       this.status = status;
    }
   
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


