package com.entitys;
// Generated 04-nov-2016 10:38:27 by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private String idUsuario;
     private String password;
     private String nombres;
     private String apellidos;
     private String pais;
     private String email;
     private String status;
     private String tipoUsuario;
     private String idAccount;

    public Usuarios() {
    }

	
    public Usuarios(String idUsuario, String password) {
        this.idUsuario = idUsuario;
        this.password = password;
    }
    public Usuarios(String idUsuario, String password, String nombres, String apellidos, String pais, String email, String status, String tipoUsuario, String idAccount) {
       this.idUsuario = idUsuario;
       this.password = password;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.pais = pais;
       this.email = email;
       this.status = status;
       this.tipoUsuario = tipoUsuario;
       this.idAccount = idAccount;
    }
   
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public String getIdAccount() {
        return this.idAccount;
    }
    
    public void setIdAccount(String idAccount) {
        this.idAccount = idAccount;
    }




}


